AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template for DayOffAPI"
Resources:
  DayOffApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: DayOffAPI
  UserHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UserHandler
      Handler: index.handler
      Runtime: python3.8
      CodeUri: ./user_handler
      Events:
        DayOffApiUser:
          Type: Api
          Properties:
            Path: /user
            Method: POST
            RestApiId: !Ref DayOffApi
  LoginHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LoginHandler
      Handler: index.handler
      Runtime: python3.8
      CodeUri: ./login_handler
      Events:
        DayOffApiLogin:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST
            RestApiId: !Ref DayOffApi
  LogoutHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LogoutHandler
      Handler: index.handler
      Runtime: python3.8
      CodeUri: ./logout_handler
      Events:
        DayOffApiLogout:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: POST
            RestApiId: !Ref DayOffApi
  TripHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TripHandler
      Handler: index.handler
      Runtime: python3.8
      CodeUri: ./trip_handler
      Events:
        DayOffApiTrip:
          Type: Api
          Properties:
            Path: /trip
            Method: POST
            RestApiId: !Ref DayOffApi
  DayOffApiStageTrip:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref DayOffApi
      StageName: trip
  DayOffApiStageUser:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref DayOffApi
      StageName: user
  DayOffApiStageAuth:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref DayOffApi
      StageName: auth

Outputs:
  DayOffApiEndpoint:
    Value: !Sub "https://${DayOffApi.ApiEndpoint}/${trip}"
    Description: URL of the DayOffAPI trip stage
